var address1 = String(process.argv[2])
var address2 = String(process.argv[3])
var address3 = String(process.argv[4])
var address4 = String(process.argv[5])
console.log("var b = Lucky7Admin.at('"+address1+"')")
console.log("var d = Lucky7Storage.at('"+address2+"')")
console.log("var c = Lucky7TicketFactory.at('"+address3+"')")
console.log("var e = Lucky7Store.at('"+address4+"')")
